name: Sync staging with master

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Merge master into staging
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Pages CMS Bot"
          git config user.email "pagescms-bot@users.noreply.github.com"

      - name: Merge master into staging
        run: |
          git checkout staging
          git pull origin master --no-edit --no-rebase
          git push origin staging
